### ISSUE TITLE
Asp.net beta 6

### ISSUE THREAD

**Issue by MaherJendoubi** [shawnwildermuth/MyCountries#3]
Would you update to asp.net beta 6 please? Thanks

**Comment by shawnwildermuth** [comment]
Feel free to fork it and I’ll accept a pull-request. It’s open source after all.

// Shawn

**Comment by MaherJendoubi** [comment]
Ok with pleasure Sir! Would you accept to correct my PR even it contains some errors?

**Comment by shawnwildermuth** [comment]
I updated it to Beta 6 and now 7. Closing this.
