### ISSUE TITLE
Page not found issue?

### ISSUE THREAD

**Issue by ianido** [shawnwildermuth/MyCountries#5]
Seems like this beta7 have an issue with page error management, if you attempt to navigate to a unexisting page I am not getting an error page, I got empty response, however the response code is still 404. Do you know how to face this?

**Comment by shawnwildermuth** [comment]
Do you mean API 'pages' or actual page URLs? We're using the error page in debug and using the error handler in release so it should work. What URL are you using to get a 404?

**Comment by ianido** [comment]
I mean page URLs, for example attempting to access to: http://localhost:port/Home/x
I get in the browser an empty page but opening fiddler I realized I get 404 from the server, do you think this is something that need to be managed by IISExpress?

**Comment by shawnwildermuth** [comment]
Solved this with the recent update that included using:

```
app.UseStatusCodePagesWithReExecute("/Home/Error/{0}");
```

Which I assumed was happening with UseErrorPage, but that only handles exceptions, not HTTP errors like 404.
